### ISSUE TITLE
MAY BE A BUG?

### ISSUE THREAD

**Issue by xxdoc** [EduardoVB/ScrollableContainer#1]
Option Explicit

Private Sub Form_Load()
   'Duplicate a bunch of controls:
   
   
   Dim I As Integer

   For I = 0 To 100

      If I > 0 Then
         Load lblData(I)
         Load txtData(I)

         With lblData(I)
            .Move lblData(0).Left, lblData(I - 1).Top + lblData(I - 1).Height + 5 * Screen.TwipsPerPixelY
            .Caption = I
            .Visible = True
        
         End With

         With txtData(I)
            .Move txtData(0).Left, txtData(I - 1).Top + txtData(I - 1).Height + 5 * Screen.TwipsPerPixelY
            .Visible = True
        
         End With

      End If

      DoEvents
   Next
    
   ScrollableContainer1.VirtualHeight = txtData(I - 1).Top + txtData(I - 1).Height
   ScrollableContainer1.VScrollBar = vxScrollBarShow
   ScrollableContainer1.HScrollBar = vxScrollBarHide
End Sub

IF I change    
 ScrollableContainer1.VScrollBar = vxScrollBarShow
   ScrollableContainer1.HScrollBar = vxScrollBarHide 
may be not scrolled

Problems arise if properties are modified.

**Comment by EduardoVB** [comment]
Now the project is an ActiveX control.
Please test with the compiled OCX.
